### ISSUE TITLE
Modify files before zip

### ISSUE THREAD

**Issue by veronicamirada** [rokucommunity/roku-deploy#28]
I would like to modify some files before zipping the project. I know the possibility of using the incrementBuildNumber parameter but it doesn't work for me because I need to change the version number in several files and I also need to remove one line from another file when build a release. I have modified the file that calls rokudeploy to receive the version as parameter, but now I don't know how to modify those files. Is it possible?

**Comment by TwitchBronBron** [comment]
Yes, that's definitely possible. You're on the right track, but the documentation appears to be lacking in this area (oops! :D). So, here's the example from the readme, modified slightly to explain how to to modify files.

```javascript
 let options = {
      host: 'ip-of-roku',
      password: 'password for roku dev admin portal'
      //other options if necessary
  };

  rokuDeploy.deploy(options, (info) => {
      //modify staging dir before it's zipped
     var stagingFolderPath = info.stagingFolderPath;
     var configFilePath = path.join(stagingFolderPath, 'src', 'someConfigFile.brs');

     //load the file as text from staging
     var text = fs.readFileSync(configFilePath).toString();

     //do something to the file text (this is where all of your custom work should go)
     text = text.replace("some_development_value", "some_production_value");

     //save the file back to staging
     fs.writeFileSync(configFilePath, text);
  }).then(function(){
      //it worked
    console.log('Build succeeded');
  }, function(e){
      //it failed
    console.error('Build failed', e);
  });
```

By the way, the callback function in `rokuDeploy.deploy` is promise-aware. So if you need to do some async work, you can do that by returning a promise in that callback function. roku-deploy will wait for the promise to resolve before starting to create the zip. Because these are single-use build scripts, there's not much benefit to using async....the sync methods will actually run faster. But figured I would at least mention it in case you want to use a library that doesn't support sync. (also not documented....I'll try to get these use cases documented soon)

**Comment by TwitchBronBron** [comment]
@veronicamirada did that work for you?

**Comment by veronicamirada** [comment]
@TwitchBronBron finally I did it on a different script because I needed to made a commit with those changes, so I first call my script and then rokudeploy from a bash script, but I think it should work!

**Comment by TwitchBronBron** [comment]
Glad you figured it out. Let us know if you run into any more issues.
